/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mabeijianxi_jianxiffmpegcmd_Test */

#ifndef _Included_com_mabeijianxi_jianxiffmpegcmd_Test
#define _Included_com_mabeijianxi_jianxiffmpegcmd_Test
#ifdef __cplusplus
extern "C" {
#endif
int MyWriteJPEG(AVFrame *pFrame,char *path, int width, int height, int iIndex);
char * MyWriteJPEG2(AVFrame *pFrame,char *path, int width, int height,int iIndex);
        char *jstringTostring(JNIEnv *env, jstring jstr);
#ifdef __cplusplus
}
#endif
#endif
