/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_esay_ffmtool_FfmpegTool */

#ifndef _Included_com_esay_ffmtool_FfmpegTool
#define _Included_com_esay_ffmtool_FfmpegTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_esay_ffmtool_FfmpegTool
 * Method:    cmdRun
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_esay_ffmtool_FfmpegTool_cmdRun
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_esay_ffmtool_FfmpegTool
 * Method:    decodToImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_esay_ffmtool_FfmpegTool_decodToImage
  (JNIEnv *, jclass, jstring, jstring, jint, jint);
/*
 * Class:     com_esay_ffmtool_FfmpegTool
 * Method:    decodToImageWithCall
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_esay_ffmtool_FfmpegTool_decodToImageWithCall
        (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
